swagger: "2.0"
info:
  title: "API"
  description: "test api"
  version: "1.0.0"
host: "hackuniversity.crabdance.com"
basePath: "/api/v1"
schemes:
  - "https"
tags:
- name: "auth"
  description: ""
paths:
  /auth:
    post:
      tags:
      - "auth"
      summary: ""
      description: "auth hello POST"
      operationId: "auth"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Request"
        required: true
        schema:
          $ref: "#/definitions/Request"
      responses:
        200:
          description: "Successfully"
          schema:
            $ref: "#/definitions/Response"
        400:
          description: &invalid_request_body "Bad request, request body is not valid"
        500:
          description: &internal_server_error "Internal server error"
      x-code-samples:
        - lang: 'cURL'
          source: |
            curl \
            -X POST \
            -H "Content-Type: application/json" \
            -d '{"key": "value"}' \
            -i \
            http://hackuniversity.crabdance.com/api/v1/hello
definitions:
  Request:
    type: "object"
    properties:
      login:
        type: "string"
      password:
        type: "string"
  Response:
    type: "object"
    properties:
      answer:
        type: integer
      data:
        type: object
        properties:
          session:
            type: "string"